# These are supported funding model platforms

# github: [boboidvtw] # Uncomment and verify if you have signed up for GitHub Sponsors
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: platform-name/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
custom: ['https://www.paypal.me/boboidvtw168']
